repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version
    rev: v0.9.4
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
#  - repo: local
#    hooks:
#      - id: ty
#        name: ty check
#        entry: uvx ty check .
#        language: python
